# Cấu hình cổng chạy ứng dụng (mặc định là 8080)
server.port=8080

# Đặt tên cho ứng dụng
spring.application.name=lab11-springboot-thymeleaf

# Cấu hình mã hóa UTF-8 để không bị lỗi tiếng Việt khi render HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html; charset=UTF-8

# Tắt cache Thymeleaf để khi sửa file .html bấm F5 trình duyệt sẽ cập nhật ngay (rất tiện khi dev)
spring.thymeleaf.cache=false